BTO_APP/grails-app/domain/com/bto/customer/EventType.groovy
package com.bto.customer

import java.util.Date;

class EventType {

    String eventType
	Date createdOn
	Date lastUpdatedOn
	
    static constraints = {
		eventType nullable:true 
		createdOn nullable:true
		lastUpdatedOn nullable:true
    }
}

BTO_APP/grails-app/controllers/com/bto/customer/AddEventTypeController.groovy
package com.bto.customer

import grails.gsp.PageRenderer;
import grails.transaction.Transactional;

class AddEventTypeController {

  PageRenderer groovyPageRenderer
	def grailsApplication

    def index() { 
		
		respond EventType.list(params), model:[eventTypeInstanceCount: EventType.count()]
	}
	
	def addEventType(){}
	
	def saveEventType(){
		try {
			def isExists=EventType.findByEventType(params?.eventType)
			if(!isExists){
				def eventType=new EventType()
				eventType.eventType=params?.eventType
				eventType.createdOn=new Date()
				eventType.lastUpdatedOn =new Date()
				
				if(eventType.save(flush:true,failOnError:true)) {
					flash.message1="Event Type Added Successfully"
					redirect action:"index"
				}
				else {
					flash.message="Error in save error event type"
					redirect action:"index"
				}
			}
			else
			{
				flash.message="Event type with this name is already exist"
				redirect action:"index"
			}
			
		} catch (Exception e) {
			e.printStackTrace()
		}
		
	}
	
	@Transactional
	def updateEventType(EventType eventTypeInstance){
		
		try{
				eventTypeInstance.eventType=params?.eventType
				eventTypeInstance.lastUpdatedOn =new Date()
				if(eventTypeInstance.save(flush:true,failOnError:true))
				{
					flash.message1="Event type Updated Successfully"
					redirect action:"index"
				}else{
					flash.message="ERROR in event type update"
					redirect action:"index"
				}
		}
		catch(Exception e)
		{
			e.printStackTrace()
		}
	}
	
	def editEventType(EventType eventTypeInstance)
	{
		respond eventTypeInstance
	}
	
	@Transactional
	def deleteEventType(EventType eventTypeInstance)
	{
		try{
			eventTypeInstance.delete(flush:true)
				flash.message1="Event type Deleted"
				redirect action:"index"
		}
		catch(Exception e)
		{
			e.printStackTrace()
		}
	}
}

BTO_APP/grails-app/views/addEventType/addEventType.gsp
<meta name="layout" content="main" />
<script>
function isCharacterKeyDot(evt)
{
    var charCode = (evt.which) ? evt.which : event.keyCode;
    // alert("Char"+charCode);
    if ((charCode >= 65 && charCode <= 90) || (charCode >= 97 && charCode <= 122) || charCode == 46 || charCode == 40 || charCode == 41 || charCode == 32 || charCode == 47 || charCode == 45 || charCode == 8 || charCode == 13){
    	document.getElementById("etype").innerHTML = "<span></span>";    	
        return true;
    }else{
    	document.getElementById("etype").innerHTML = "<span style='color:red;'>Only a-z A-Z digits allowed...!</span>";
        return false;
    }
}

</script>
<div class="row">
	<div class="col-sm-12">
		<div class="">
			<h4 class="m-t-0 header-title">
				<b>New Event Type</b>
			</h4>
			<div class="col-md-2"></div>
			<g:if test="${flash.message}">
				<div class="message" role="status">
					${flash.message}
				</div>
			</g:if>
			<g:if test="${flash.message1}">
				<div class="message1" role="status">
					${flash.message1}
				</div>
			</g:if>
			<div class="col-md-8">
				<g:form controller="AddEventType" action="saveEventType" method="post">
					<div>

						
						<div class="form-group clearfix">
							<label class="col-lg-3 control-label" for="name2">Event Type *</label>
							<div class="col-lg-9">
								<input id="name2" name="eventType" type="text" class="form-control" required="required" oninvalid="this.setCustomValidity('Enter event type')"
											onchange="this.setCustomValidity('')" onkeypress="return isCharacterKeyDot(event);">
											<div id="etype" style="color:red;"></div>
							</div>
						</div>
						
						<div class="form-group clearfix">
							<div class="col-lg-3" style="float: right;">
								<button class="btn btn-success waves-effect waves-light"
									type="submit">Submit</button>
								&nbsp;
								<g:link action="index"
									class="btn btn-inverse waves-effect waves-light">Cancel</g:link>
							</div>
						</div>


					</div>
				</g:form>
			</div>
			<div class="col-md-2"></div>
		</div>
	</div>
</div>
<!-- End row -->

BTO_APP/grails-app/views/addEventType/editEventType.gsp
<meta name="layout" content="main" />
<script>
function isCharacterKeyDot(evt)
{
    var charCode = (evt.which) ? evt.which : event.keyCode;
    // alert("Char"+charCode);
    if ((charCode >= 65 && charCode <= 90) || (charCode >= 97 && charCode <= 122) || charCode == 46 || charCode == 40 || charCode == 41 || charCode == 32 || charCode == 47 || charCode == 45 || charCode == 8 || charCode == 13){
    	document.getElementById("etype").innerHTML = "<span></span>";    	
        return true;
    }else{
    	document.getElementById("etype").innerHTML = "<span style='color:red;'>Only a-z A-Z digits allowed...!</span>";
        return false;
    }
}
</script>
<div class="row">
	<div class="col-sm-12">
		<div class="">
			<h4 class="m-t-0 header-title">
				<b>Update Event Type</b>
			</h4>
			<div class="col-md-2"></div>
			<g:if test="${flash.message}">
				<div class="message" role="status">
					${flash.message}
				</div>
			</g:if>
			<g:if test="${flash.message1}">
				<div class="message1" role="status">
					${flash.message1}
				</div>
			</g:if>
			<div class="col-md-8">
				<g:form action="updateEventType" controller="AddEventType" method="post">
					<div>
						<g:hiddenField name="id" value="${eventTypeInstance?.id}" />
						<div class="form-group clearfix">
							<label class="col-lg-3 control-label" for="name2">Event Type *</label>
							<div class="col-lg-9">
								<input id="name2" name="eventType" type="text" class="form-control" required="required" oninvalid="this.setCustomValidity('Enter event type')"
											onchange="this.setCustomValidity('')" onkeypress="return isCharacterKeyDot(event);" value="${eventTypeInstance?.eventType}">
											<div id="etype" style="color:red;"></div>
							</div>
						</div>
						<div class="form-group clearfix">
							<div class="col-lg-3" style="float: right;">
								<button class="btn btn-success waves-effect waves-light" type="submit">Update</button>
									&nbsp;<g:link controller="AddVendor" action="index" class="btn btn-inverse waves-effect waves-light">Cancel</g:link>
							</div>
						</div>


					</div>
				</g:form>
			</div>
			<div class="col-md-2"></div>
		</div>
	</div>
</div>
<!-- End row -->

BTO_APP/grails-app/views/addEventType/index.gsp
<meta name="layout" content="main"/>
 <link href="${resource(dir:'assets/plugins/datatables',file:'jquery.dataTables.min.css')}" rel="stylesheet" type="text/css" />
<link href="${resource(dir:'assets/plugins/datatables',file:'fixedHeader.bootstrap.min.css')}" rel="stylesheet" type="text/css" />
<link href="${resource(dir:'assets/plugins/datatables',file:'responsive.bootstrap.min.css')}" rel="stylesheet" type="text/css" />
<link href="${resource(dir:'assets/plugins/datatables',file:'scroller.bootstrap.min.css')}" rel="stylesheet" type="text/css" />
<link href="${resource(dir:'assets/plugins/datatables',file:'dataTables.colVis.css')}" rel="stylesheet" type="text/css" />
<h4 class="m-t-0 header-title">
		<b>Event Type List</b>
</h4>
<div class="col-md-12" style="text-align:right">
	<g:link controller="AddEventType" action="addEventType" class="btn btn-success waves-effect waves-light" style="float:right;"> New Event Type</g:link>
<br><br>
</div>
<div class="row" style="margin-top: 5%;">
	<g:if test="${flash.message}">
		<div class="message" role="status">
			${flash.message}
		</div>
	</g:if>
	<g:if test="${flash.message1}">
		<div class="message1" role="status">
			${flash.message1}
		</div>
	</g:if>
	
	<div class="col-md-1"></div>
<div class="col-md-10">
	<table id="datatable" class="table table-striped table-bordered">
		<thead>
			<tr>
				
				<th>Event Type</th>
				<th>Actions</th>
			</tr>
			</thead>
			<tbody>
			<g:each in="${eventTypeInstanceList}" status="i" var="eventTypeInstance">
				<tr>
				<%--<td align="center" style="border:0">${eventTypeInstance?.id}</td>--%>
				<td>${eventTypeInstance?.eventType}</td>
				
				<td>
				<g:link action="editEventType" id="${eventTypeInstance?.id}" title="Edit"><i class="md  md-edit"></i></g:link>
				
				 | 
				<g:link action="deleteEventType" id="${eventTypeInstance?.id}" title="Delete" onclick="return confirm(' You want to delete?');"><i class="md  md-delete"></i></g:link>
				
				</td>
				</tr>
			</g:each>			
		</tbody>
	</table>
</div>
<div class="col-md-1"></div>
</div>
<script src="${resource(dir:'assets/js',file:'jquery.min.js')}"></script>
<script src="${resource(dir:'assets/plugins/datatables',file:'jquery.dataTables.min.js')}"></script>
<script src="${resource(dir:'assets/plugins/datatables',file:'dataTables.bootstrap.js')}"></script>
<script src="${resource(dir:'assets/plugins/datatables',file:'dataTables.scroller.min.js')}"></script>
<script type="text/javascript">
            $(document).ready(function() {
                $('#datatable').dataTable();
            });
          </script>