BTO_APP/grails-app/domain/com/bto/user/AlertTypes.groovy
package com.bto.user

class AlertTypes {

   String alertType
	String message
	Date createdOn
	Date lastUpdatedOn

    static constraints = {
		
		alertType(nullable:false)
		message(nullable:false)
		createdOn(nullable:false)
		lastUpdatedOn(nullable:false)
		
    }
}

BTO_APP/grails-app/domain/com/bto/user/CorporateUser.groovy
package com.bto.user

class CorporateUser {

  String emailID
	String firstName
	String lastName
	Integer status
	
    static constraints = {
		emailID nullable:false,unique: true, blank:false, email:true
		firstName blank:false
		lastName blank:false
		status nullable:true
		}
}

BTO_APP/grails-app/domain/com/bto/user/User.groovy
package com.bto.user

import java.lang.String.CaseInsensitiveComparator;
import java.util.Date;

class User {

    transient springSecurityService
	static transients = ['springSecurityService']
	
	// Login credentials
	String emailID
	String password
	// Personal Details
	String firstName
	String lastName
	String phone
	String costCenter
	Boolean status
	
	//after registration required fields
	String gender
	String countryCodePhone
	String dob
	String linkedInID
	String facebookID
	String profilePicture
	String department
	String designation
	String timeZone
	String address
	
	Date createdOn
	Date lastUpdatedOn

	static constraints = {
		emailID nullable:false,unique: true, blank:false, email:true
		password blank:false
		firstName blank:false,  nullable:true
		lastName blank:false,  nullable:true
		phone nullable:true
		costCenter  nullable:true
		status nullable:true
		
		gender nullable:true 
		countryCodePhone nullable:true 
		dob nullable:true 
		linkedInID nullable:true 
		facebookID nullable:true 
		profilePicture nullable:true 
		department nullable:true 
		designation nullable:true 
		timeZone nullable:true 
		address nullable:true 
		
		createdOn nullable:true
		lastUpdatedOn nullable:true
	}
	
	def beforeInsert() {
		encodePassword()
	}

	def beforeUpdate() {
		if (isDirty('password')) {
			encodePassword()
		}
	}

	protected void encodePassword() {
		//password = springSecurityService?.passwordEncoder ? springSecurityService.encodePassword(password) : password
	}
}

BTO_APP/grails-app/domain/com/bto/user/UserAlerts.groovy
package com.bto.user

import java.util.Date;

import com.bto.customer.VendorDetails;
import com.bto.trip.EventDetails;
import com.bto.trip.InviteDetails;
import com.bto.trip.TripDetails

class UserAlerts {

    User sender
	User receiver
	AlertTypes alertType
	String smsText
	String type
	TripDetails trip
	VendorDetails vendor
	InviteDetails invite
	String status="Unread"
	EventDetails event
	Date createdOn
	Date lastUpdatedOn
	
    static constraints = {
		
		sender(nullable:true)
		receiver(nullable:false)
		alertType(nullable:true)
		smsText(nullable:true)
		type(nullable:true,inList:['TripAlert', 'SMS','EventAlert','Account'])
		createdOn(nullable:true)
		trip(nullable:true)
		status(nullable:true,inList:['Read', 'Unread'])
		lastUpdatedOn(nullable:true)
		vendor nullable:true
		invite nullable:true
		event nullable:true 
    }
}

BTO_APP/grails-app/domain/com/bto/user/UserDeviceToken.groovy
package com.bto.user

import java.util.Date;

class UserDeviceToken {

   User user
	String deviceType
	String deviceToken
	Boolean status
	Date createdOn
	Date lastUpdatedOn
	String apitoken

		static constraints = {

		deviceType nullable:true
		deviceToken nullable:true
		status nullable:true
		createdOn nullable:true
		lastUpdatedOn nullable:true
		apitoken nullable:true		
	}
}

BTO_APP/grails-app/domain/com/bto/user/VerificationDetails.groovy
package com.bto.user

import java.util.Date;

class VerificationDetails {

   User user
	String emailID
	String phoneVerificationCode
	Boolean isPhoneVerified
	Date createdOn
	Date lastUpdatedOn
	
    static constraints = {
		user nullable:true
		emailID nullable:true
		phoneVerificationCode nullable:true 
		isPhoneVerified nullable:true 
		createdOn nullable:true 
		lastUpdatedOn nullable:true  
    }
	
}

BTO_APP/grails-app/controllers/com/bto/user/UserController.groovy
package com.bto.user

import grails.plugins.rest.client.RestBuilder
import groovy.json.JsonSlurper;

import java.io.IOException;
import java.io.Reader;
import java.nio.charset.Charset;

import org.apache.commons.codec.binary.Base64;
import org.codehaus.groovy.grails.web.json.JSONObject
import org.springframework.web.multipart.MultipartFile

import com.bto.booking.BookingConsoleController;
import com.bto.utilities.UtilitiesService;

class UserController {

	def grailsApplication
	def bookingConsole
	def index() { }

	def register(){}
	def userProfile(){
		def user=User.get(session['userID'])
		respond User.findAllByEmailID(user.emailID), model:[userInstanceCount: User.count()]
	}
	def userVerification(){}
	def changePassword(){}

	// method to call registerUser service
	def saveUser(){
		try {

			// if user is valid then call registerUser web service
			def web="web" // set device type as web
			InputStream is1 = new URL(grailsApplication.config.grails.webSite+"WebService/registerUser?emailID="+params?.emailID+"&password="+params?.password+"&firstName="+params?.firstName+"&lastName="+params?.lastName+"&phone="+params?.phone+"&costCenter="+params?.costCenter+"&deviceType="+web+"&deviceToken="+web).openStream();
			BufferedReader rd1 = new BufferedReader(new InputStreamReader(is1, Charset.forName("UTF-8")));
			String jsonText1 =UtilitiesService.readAll(rd1);
			JSONObject json1 = new JSONObject(jsonText1);
			if(json1.getString("response")=="success") {
				flash.message1="Registration Successfull...!"
				session["userID"]=json1.getString("userId")
				session["emailID"]=json1.getString("emailID")
				session["phone"]=json1.getString("phone")
				session["firstName"]=json1.getString("firstName")
				session["lastName"]=json1.getString("lastName")
				session["designation"]=json1.getString("designation")
				session["costCenter"]=json1.getString("costCenter")
				session["role"]="User"
				session["profilePicture"]=json1.getString("profilePicture")
				redirect(action: "userVerification")
			}
			else {
				flash.message=json1.getString("errorList").toString()
				redirect action:"register"
			}
		}
		catch (Exception e) {
			e.printStackTrace()
		}
	}

	// method to send verification code to user mobile
	def validateUser(){
		//checking verification code
		InputStream is2 = new URL(grailsApplication.config.grails.webSite+"WebService/userVerification?emailID="+params?.emailID+"&verificationCode="+params?.verificationCode+"&phone="+params?.phone+"&firstName="+params?.firstName).openStream();
		BufferedReader rd2 = new BufferedReader(new InputStreamReader(is2, Charset.forName("UTF-8")));
		String jsonText2 =UtilitiesService.readAll(rd2);
		JSONObject json2 = new JSONObject(jsonText2);
		if(json2.getString("response")=="success") {
			//set session
			session["userID"]=json2.getString("userId")
			session["emailID"]=json2.getString("emailID")
			session["phone"]=json2.getString("phone")
			session["firstName"]=json2.getString("firstName")
			session["role"]="User"
			//flash.message1="Verification Successful...!"
			redirect(controller:"BookingConsole", action: "index")
		}
		else {

			flash.message="Error in verification...!"+json2.getString("errorList").toString()
			session["emailID"]=json2.getString("emailID")
			session["phone"]=json2.getString("phone")
			session["firstName"]=json2.getString("firstName")
			session["role"]="User"
			redirect(action: "userVerification")
		}
	}

	// method to resent verification code to user mobile
	def resendVerificationCode(){

		InputStream is = new URL(grailsApplication.config.grails.webSite+"WebService/resendVerificationCode?emailID="+params?.emailID+"&phone="+params?.phone+"&firstName="+params?.firstName).openStream();
		BufferedReader rd = new BufferedReader(new InputStreamReader(is, Charset.forName("UTF-8")));
		String jsonText=UtilitiesService.readAll(rd);
		JSONObject json = new JSONObject(jsonText);
		if(json.getString("response")=="success") {
			flash.message1="Code sent successfully...!"
			session["emailID"]=json.getString("emailID")
			session["phone"]=json.getString("phone")
			session["firstName"]=json.getString("firstName")
			session["role"]="User"
			redirect(action: "userVerification")
		}
		else {
			session["emailID"]=json.getString("emailID")
			session["phone"]=json.getString("phone")
			session["firstName"]=json.getString("firstName")
			flash.message="Error in resending verification code...!"+json.getString("errorList").toString()
			redirect(action: "userVerification")
		}
	}

	// method to login user with given credentials
	def authenticateUser(){
		InputStream is = new URL(grailsApplication.config.grails.webSite+"WebService/authenticateUser?emailID="+params?.emailID+"&password="+params?.password+"&deviceToken="+params?.deviceToken+"&deviceType="+params?.deviceType).openStream();
		BufferedReader rd = new BufferedReader(new InputStreamReader(is, Charset.forName("UTF-8")));
		String jsonText =UtilitiesService.readAll(rd);
		JSONObject json = new JSONObject(jsonText);
		JsonSlurper jslurp=new JsonSlurper()
		Object obj=jslurp.parseText(jsonText)
		Map jsonData=(Map)obj

		if(json.getString("response")=="success") {
			//set session
			session["userID"]=json.getString("userId")
			session["emailID"]=json.getString("emailID")
			session["phone"]=json.getString("phone")
			session["firstName"]=json.getString("firstName")
			session["lastName"]=json.getString("lastName")
			session["designation"]=json.getString("designation")
			session["costCenter"]=json.getString("costCenter")
			session["role"]="User"
			session["profilePicture"]=json.getString("profilePicture")

			if(json.getString("isPhoneVerified")=="false"){
				flash.message="Please Verify before Login...!"
				redirect(action: "userVerification")
			}else{
				redirect(controller:"BookingConsole", action: "index")
			}
		}
		else {

			flash.message=jsonData.get("errorList")[0]
			//redirect(action: "userVerification")
			redirect(action: "index")
		}
	}

	def changePass(){

		InputStream is = new URL(grailsApplication.config.grails.webSite+"WebService/changePassword?emailID="+params?.emailID+"&oldPassword="+params?.oldPassword+"&newPassword="+params?.newPassword+"&confirmPassword="+params?.confirmPassword).openStream();
		BufferedReader rd = new BufferedReader(new InputStreamReader(is, Charset.forName("UTF-8")));
		String jsonText =UtilitiesService.readAll(rd);
		JSONObject json = new JSONObject(jsonText);
		JsonSlurper jslurp=new JsonSlurper()
		Object obj=jslurp.parseText(jsonText)
		Map jsonData=(Map)obj

		if(json.getString("response")=="success") {
			flash.message1="Password Changed Successfully...!"
			redirect(action: "userProfile")
		}
		else {
			flash.message=jsonData.get("errorList")[0]
			redirect(action: "changePassword")
		}
	}

	def forgotPassword(){
		InputStream is = new URL(grailsApplication.config.grails.webSite+"WebService/forgotPassword?emailID="+params?.emailID).openStream();
		BufferedReader rd = new BufferedReader(new InputStreamReader(is, Charset.forName("UTF-8")));
		String jsonText =UtilitiesService.readAll(rd);
		JSONObject json = new JSONObject(jsonText);
		JsonSlurper jslurp=new JsonSlurper()
		Object obj=jslurp.parseText(jsonText)
		Map jsonData=(Map)obj

		if(json.getString("response")=="success") {
			flash.message1="Password sent to your email address..!"
			redirect(action: "index")
		}
		else {
			flash.message=jsonData.get("errorList")[0]
			redirect(action: "index")
		}
	}

	def updateUserProfile(){

		try {
			MultipartFile profilePicture
			session["phone"]=params?.phone
			session["costCenter"]=params?.costCenter
			def fileExt
			byte[] encoded
			String encodedString=""
			profilePicture=params?.profileImage
			//def contentType =profilePicture.contentType
			def picSize = profilePicture.size
			fileExt=profilePicture.getOriginalFilename().tokenize(".")
				encoded=Base64.encodeBase64URLSafeString(profilePicture.getBytes())
			encodedString=new String(encoded)
			RestBuilder rest=new RestBuilder()
			def resp = rest.get(grailsApplication.config.grails.webSite+"WebService/updateUserProfile?emailID="+params?.emailID+"&phone="+params?.phone+"&dob="+params?.dob+"&gender="+params?.gender+"&department="+params?.department+"&designation="+params?.designation+"&costCenter="+params?.costCenter+"&profileImage="+encodedString+"&profilePicContentType="+fileExt[1])
			resp.json instanceof JSONObject
			//parse JSON response using JsonSlurper
			def JsonSlurper=new JsonSlurper()
			def object=JsonSlurper.parseText(resp.json.toString())
			//Get parent ArrayList called "Result"
			def resultList=object.errorList
			//Get 1st Object from ResultList
			def error=resultList[0]

			if(resp.json.response=="success") {
				flash.message1="Profile updated successfully..!"
				redirect(action: "userProfile")
			}
			else {
				flash.message=error
				redirect(action: "userProfile")
			}
		} catch (Exception e) {
			e.printStackTrace()
		}


	}

}

BTO_APP/grails-app/views/user/changePassword.gsp
<%@ page contentType="text/html;charset=UTF-8"%>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
<meta name="layout" content="main" />
<title>Change Password</title>
<style type="text/css">
html, body {
	background: #FFFFFF;
}

.card-box { //
	box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0
		rgba(0, 0, 0, 0.19);
	box-shadow: 1px 1px 5px #aeaeae;
	background-color: transparent;
}
</style>
<script>
function validatePassword() {
var oldPassword,newPassword,confirmPassword,output = true;

oldPassword = document.frmChange.oldPassword;
newPassword = document.frmChange.newPassword;
confirmPassword = document.frmChange.confirmPassword;

if(!oldPassword.value) {
	oldPassword.focus();
	document.getElementById("oldPassword").innerHTML = "required";
	output = false;
}
else if(!newPassword.value) {
	newPassword.focus();
	document.getElementById("newPassword").innerHTML = "required";
	output = false;
}
else if(!confirmPassword.value) {
	confirmPassword.focus();
	document.getElementById("confirmPassword").innerHTML = "required";
	output = false;
}
if(newPassword.value != confirmPassword.value) {
	newPassword.value="";
	confirmPassword.value="";
	newPassword.focus();
	document.getElementById("confirmPassword").innerHTML = "<span style=\"color:red\">New and confirm password does not match</span>";
	output = false;
} 	
return output;
}
</script>
</head>
<body>
	<div class="body">
				<div class=" card-box" style="padding: 0px;width: 34%;margin-left: 30%;">
			<div class="panel-heading">
				<h3 class="" style="text-align: center;">Change password</h3>
				
				<g:if test="${flash.message}">
						<div class="message" role="status">
							${flash.message}
						</div>
				</g:if>
				<g:if test="${flash.message1}">
						<div class="message1" role="status">
							${flash.message1}
						</div>
				</g:if>
				<div class="panel-body">
					<g:form class="form-horizontal m-t-20" controller="User" action="changePass" onSubmit="return validatePassword()" name="frmChange">
						<input type="hidden" name="emailID" value="${session['emailID'] }"/>
						<div class="form-group">
							<div class="col-md-12">
								<label>Old Password*</label> <input class="form-control" name="oldPassword"
								oninvalid="this.setCustomValidity('Enter old password')"
												onchange="this.setCustomValidity('')"
									type="password" required="" placeholder="Enter old password">
									<span id="oldPassword"  class="required"></span>
							</div>
						</div>
						<div class="form-group">
							<div class="col-md-12">
								<label>New Password*</label> <input class="form-control" name="newPassword"
								oninvalid="this.setCustomValidity('Enter new password')"
												onchange="this.setCustomValidity('')"
									type="password" required="" placeholder="Enter new password">
									<span id="newPassword"  class="required"></span>
							</div>
						</div>
						<div class="form-group">
							<div class="col-md-12">
								<label>Confirm Password*</label> <input class="form-control" name="confirmPassword"
								oninvalid="this.setCustomValidity('Confirm new password')"
								onchange="this.setCustomValidity('')"	type="password" required="" placeholder="Confirm new password">
									<span id="confirmPassword"  class="required"></span>
							</div>
						</div>
						
						<div class="form-group text-center m-t-30">
							<div class="col-md-12">
								<button	class="btn btn-success  text-uppercase waves-effect waves-light"
									type="submit" style="width: 40%;">Submit</button>
							</div>
						</div>
					</g:form>
					

			</div>
		</div>
				</div>
			</div>
<script type="text/javascript">
$(document).ready(function(){
<%
session['sidebarActive']="";
session['sidebarActive']="user/changePassword";
%>
});
</script>
</body>
</html>

BTO_APP/grails-app/views/user/userProfile.gsp
<%@ page contentType="text/html;charset=UTF-8"%>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
<meta name="layout" content="main" />
<title>Profile | BTO</title>
<%--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
--%>

<link rel="stylesheet"	href="${resource(dir:'assets/plugins/timepicker',file:'bootstrap-timepicker.min.css') }">
<link rel="stylesheet"	href="${resource(dir:'assets/plugins/mjolnic-bootstrap-colorpicker/dist/css',file:'bootstrap-colorpicker.min.css') }">
<link rel="stylesheet"	href="${resource(dir:'assets/plugins/bootstrap-datepicker/dist/css',file:'bootstrap-datepicker.min.css') }">
<link rel="stylesheet"	href="${resource(dir:'assets/plugins/clockpicker/dist',file:'jquery-clockpicker.min.css') }">
<link rel="stylesheet"	href="${resource(dir:'assets/plugins/bootstrap-daterangepicker',file:'daterangepicker.css') }">


<style type="text/css">
html, body {
	background: #FFFFFF;
}

.card-box {
	//box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0	rgba(0, 0, 0, 0.19);
	 box-shadow: 1px 1px 5px #aeaeae;
	 background-color: transparent;
}



</style>

 <script>
            function check(x) {
                var user = x;
               
                if (user == "disp") {
                    $("#editProfile").css("display", "");
                    $("#showProfile").css("display", "none");
                }
                if (user == "edit") {
                    $("#showProfile").css("display", "");
                    $("#editProfile").css("display", "none");

                }
            }
        </script>
<script>
function isNumberKey(evt)
{
    var charCode = (evt.which) ? evt.which : event.keyCode;
    // alert("Number"+charCode);
    if (charCode > 31 && (charCode < 48 || charCode > 57)){
		document.getElementById("mob").innerHTML = "<span style='color:red;'>Only 0-9 digits allowed...!</span>"; 
	 return false;
	}
       
    else{
    document.getElementById("mob").innerHTML = "<span></span>";
	return true;
	}
}
function isCharacterKeyDot(evt)
{
    var charCode = (evt.which) ? evt.which : event.keyCode;
    // alert("Char"+charCode);
    if ((charCode >= 65 && charCode <= 90) || (charCode >= 97 && charCode <= 122) || charCode == 46 || charCode == 40 || charCode == 41 || charCode == 32 || charCode == 47 || charCode == 45 || charCode == 8 || charCode == 13){
    	document.getElementById("desig").innerHTML = "<span></span>";    	
        return true;
    }else{
    	document.getElementById("desig").innerHTML = "<span style='color:red;'>Only a-z A-Z digits allowed...!</span>";
        return false;
    }
}
function isCharacterKeyDot1(evt)
{
    var charCode = (evt.which) ? evt.which : event.keyCode;
    // alert("Char"+charCode);
    if ((charCode >= 65 && charCode <= 90) || (charCode >= 97 && charCode <= 122) || charCode == 46 || charCode == 40 || charCode == 41 || charCode == 32 || charCode == 47 || charCode == 45 || charCode == 8 || charCode == 13){
    	document.getElementById("dept").innerHTML = "<span></span>";    	
        return true;
    }else{
    	document.getElementById("dept").innerHTML = "<span style='color:red;'>Only a-z A-Z digits allowed...!</span>";
        return false;
    }
}
</script>
</head>
<body>
	<div class="body">
		
					<g:each var="user" in="${userInstanceList}" status="i">
						<div class="profile-detail card-box" id="showProfile" style="width: 40%;margin-left: 30%;">
						<p onclick="check('disp');"><i class="glyphicon glyphicon-pencil" style="float: right;"></i></p>
							<div>
							<g:if test="${flash.message}">
								<div class="message" role="status">
									${flash.message}
								</div>
							</g:if>
							<g:if test="${flash.message1}">
								<div class="message1" role="status">
									${flash.message1}
								</div>
							</g:if>
							<g:if test="${user?.profilePicture.toString().equals('') }">
							<g:set var="profilePic" value="user.png"></g:set>
							</g:if>
							<g:else>
							<g:set var="profilePic" value="${user?.profilePicture}"></g:set>
							</g:else>
							<img src="${resource(dir:'images/userProfilePictures',file:profilePic)}" class="img-circle" alt="profile-image" />
								


								<h4 class="font-600">${session['firstName']} ${session['lastName'] }</h4>
	
								
								<div style="margin-left:-10px%;" class="panel-body form-horizontal m-t-10">
									
										<div class="form-group form-horizontal m-t-10">
											<div class="col-md-6" style="text-align: left;">
												<label>Email address</label>
												<p>${session['emailID']}</p>
											</div>											
											<div class="col-md-6" style="text-align: center;">
												
												<label>Mobile</label>
												<p>${session['phone']}</p>
											</div>
										</div>
										
															
										<div class="form-group form-horizontal m-t-10">
											<div class="col-md-6" style="text-align: left;">
												<label>Date of Birth</label>
												<p>${user?.dob}</p>
											</div>
											
											<div class="col-md-6" style="text-align: center;">
												<label>Gender</label>
												<p>${user?.gender}</p>
											</div>
										</div>
										<div class="form-group form-horizontal m-t-10">
											<div class="col-md-6" style="text-align: left;">
												<label>Department</label>
												<p>${user?.department}</p>
											</div>
											
											<div class="col-md-6" style="text-align: center;">
												<label>Designation</label>
												<p>${user?.designation}</p>
											</div>
										</div>	
										<div class="form-group form-horizontal m-t-10">
											<div class="col-md-6" style="text-align: left;">
											<label>Cost center</label>
												<p>${session['costCenter']}</p>
											</div>
											
											<div class="col-md-6" style="text-align: center;">
												
											</div>
										</div>	
								</div>
								
							</div>
						</div>
						
						<div class="profile-detail card-box" id="editProfile" style="width: 40%;margin-left: 30%;display: none">
						<p onclick="check('edit');"><i class="glyphicon  glyphicon-remove" style="float: right;"></i></p>
						<g:uploadForm action="updateUserProfile" controller="User" method="post">
						<div>
								<div class="show-image">
								<img src="${resource(dir:'images/userProfilePictures',file:profilePic)}" class="img-circle" alt="profile-image" />
								<input type="file" name="profileImage">
								</div>


								<h4 class="font-600">${session['firstName']} ${session['lastName'] }</h4>

				
								<div style="margin-left:-10px%;" class="panel-body form-horizontal m-t-0">
									
										<div class="form-group form-horizontal m-t-0">
											<div class="col-md-6" style="text-align: left;">
												<label>Email address</label>
												<p>${session['emailID']}</p>
												<input type="hidden" name="firstName" value="${session['firstName']}">
												<input type="hidden" name="lastName" value="${session['lastName']}">
												<input type="hidden" name="emailID" value="${session['emailID']}">
											</div>											
											<div class="col-md-6" style="text-align: center;">
												
												<label>Mobile</label>
												<p><input class="form-control"
												oninvalid="this.setCustomValidity('Enter mobile number')" value="${session['phone']}"
												onchange="this.setCustomValidity('')"
										name="phone" type="text" required="" maxlength="10"
										placeholder="Enter mobile number"></p>
											</div>
										</div>
										
															
										<div class="form-group form-horizontal m-t-0">
											<div class="col-md-6" style="text-align: left;">
											<label>Date of Birth</label>
												<p>
												
												<input type="text" class="form-control"
													data-date-format='dd/mm/yyyy' name="dob" value="${user?.dob}"
													placeholder="dd/mm/yyyy" id="datepicker">												
												</p>												
											</div>
											
											<div class="col-md-6" style="text-align: center;">
												<label>Gender</label>
												<p><input type="radio" name="gender" value="Male">Male &nbsp;&nbsp;&nbsp;<input type="radio" name="gender" value="Female">Female</p>
											</div>
										</div>
										<div class="form-group form-horizontal m-t-0">
											<div class="col-md-6" style="text-align: left;">
												<label>Department</label>
												<p><input class="form-control" name="department" type="text" 
										oninvalid="this.setCustomValidity('Enter department')" value="${user?.department}" onkeypress="return isCharacterKeyDot1(event);"
												onchange="this.setCustomValidity('')"
										placeholder="Enter department">
										<div id="dept" style="color:red;"></div></p>
											</div>
											
											<div class="col-md-6" style="text-align: center;">
												<label>Designation</label>
												<p><input class="form-control" name="designation" type="text" 
												oninvalid="this.setCustomValidity('Enter designation')" value="${user?.designation}" onkeypress="return isCharacterKeyDot(event);"
												onchange="this.setCustomValidity('')" placeholder="Enter designation">
												<div id="desig" style="color:red;"></div>
												</p>
											</div>
										</div>	
										<div class="form-group form-horizontal m-t-0">
											<div class="col-md-6" style="text-align: left;">
											<label>Cost center</label>
												<p><input class="form-control" name="costCenter" type="text" required=""
												oninvalid="this.setCustomValidity('Enter cost center')" value="${session['costCenter']}"
												onchange="this.setCustomValidity('')" placeholder="Enter cost center"></p>
											</div>
											
											<div class="col-md-6" style="text-align: center;">
												
											</div>
										</div>	
										<button class="btn btn-success waves-effect waves-light" style="width: 40%;"
											type="submit">Update</button>	
								</div>



						</div>
						</g:uploadForm>
					</div>
					</g:each>
				</div>
			<div class="col-md-4"></div>
<script type="text/javascript">
$(document).ready(function(){
<%
session['sidebarActive']="";
session['sidebarActive']="user/userProfile";
%>
});
</script>
</body>
</html>